version: 2
updates:
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: monthly
  commit-message:
      # Prefix all commit messages with "[docker] " (no colon, but a trailing whitespace)
      prefix: "[dependabot] "
  open-pull-requests-limit: 5
  ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
